name: Cypress E2E Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch: # allows manual trigger from GitHub UI
    inputs:
        environment:
            description: 'Target environment'
            required: true
            default: 'staging'
            type: choice
            options:
                - staging
                - local-ephimeral

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cypress-run:
    name: Cypress E2E
    runs-on: ubuntu-latest
    timeout-minutes: 30 # hard kill if tests hang
    environment: ${{ github.event.inputs.environment || 'stagging' }}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Debug secrets
        run: |
          echo "Environment: ${{ github.event.inputs.environment || 'staging' }}"
          echo "BASE_URL is set: ${{ secrets.BASE_URL != '' }}"

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run cy:run:full:cicd -- --env BASE_URL=${{ secrets.BASE_URL }}

      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 7

      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 7